### ISSUE TITLE
Gruppierung zusätzlich nach User Stories

### ISSUE THREAD

**Issue by htl-leonding** [stefnotch/youtrack-diagram#1]
Hallo,
wäre es möglich die Tasks nicht nur nach Sprints sondern (pr Button, Checkbox, etc...) auch nach User Stories zu gruppieren
Vielen Dank
mfg TS

**Comment by stefnotch** [comment]
Jetzt ist es leichter User Stories von Tasks zu unterscheiden
https://github.com/stefnotch/youtrack-diagram/issues/2
